layout_spectrum: 0.7678970661945641
typography_spectrum: 0.9451013214420527
color:
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
  brandStrength: 0.3439944093115628
  lightness: 0.4743662152905017
  saturation: 0.8998195249587297
  rhythmicContrast: 0.7190648950636387
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
name: The Cheeky Pup
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Dublin 8 - Pupp cafe
    id: b2493604-09b0-4e1c-b94f-04a1e5ff512e
    type: content
  - name: Dublin 8 - MVP - Cafe & Bar
    id: ec79a1d2-8cfc-4739-be9a-238c4b1806cb
    type: content
favicon: null
title: ''
description: ''
purpose: []
