typography_spectrum: 0.18204173864796758
color:
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
  brandStrength: 0.25501085189171135
  lightness: 0.7881172106135637
  saturation: 0.8098408847581595
  rhythmicContrast: 0.44652708270587027
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.44171388377435505
analytics:
  google: null
  facebook: null
  twitter: null
name: The Cheeky Pup
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Dublin 8 - Pupp cafe
    id: b2493604-09b0-4e1c-b94f-04a1e5ff512e
    type: content
  - name: Dublin 8 - MVP - Cafe & Bar
    id: ec79a1d2-8cfc-4739-be9a-238c4b1806cb
    type: content
favicon: null
title: ''
description: ''
purpose: []
