typography_spectrum: 0.98223
color:
  brandColors:
    - '#e5f4fb'
    - '#274079'
    - '#a3a0a5'
    - '#9d7247'
    - '#1e0d17'
  brandStrength: 0
  lightness: 0.25
  saturation: 1
  rhythmicContrast: 0
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.76058
analytics:
  google: null
  facebook: null
  twitter: null
name: Pet Friendly
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: The Cheeky Pup
description: Places for paws
purpose: []
