name: Pet Friendly
favicon: null
layout_spectrum: 0.76058
typography_spectrum: 0.98223
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e5f4fb'
    - '#274079'
    - '#a3a0a5'
    - '#9d7247'
    - '#1e0d17'
  brandStrength: 0.0625
  lightness: 0.25
  saturation: 0.34755333070643246
  rhythmicContrast: 0.3306814110837877
purpose: []
