name: Pet Friendly
favicon: null
layout_spectrum: 0.99069
typography_spectrum: 0.24964243965223432
title: Your definitive guide to pet friendly resources
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#dbb85c'
    - '#f1f2ed'
    - '#703220'
    - '#b46542'
  brandStrength: 0.0997922932729125
  lightness: 0.05199862131848931
  saturation: 0.34755333070643246
  rhythmicContrast: 0.3306814110837877
purpose: []
